// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAK0eYDK3ZfhOUI8CoZIOFLumxbOoWfeg',
    appId: '1:624595173117:web:1ef4ef8a5024477e484894',
    messagingSenderId: '624595173117',
    projectId: 'international-student-4a94a',
    authDomain: 'international-student-4a94a.firebaseapp.com',
    storageBucket: 'international-student-4a94a.appspot.com',
    measurementId: 'G-FC2LPJ0ZFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCpBtIRKSyrINMVEBXMr66ZyytB15vK3k',
    appId: '1:624595173117:android:799ee19aab502c61484894',
    messagingSenderId: '624595173117',
    projectId: 'international-student-4a94a',
    storageBucket: 'international-student-4a94a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtH1JX6aBVbfLa3Cru5h09A3a7PQGTO9U',
    appId: '1:624595173117:ios:b76bc5d623a0cf64484894',
    messagingSenderId: '624595173117',
    projectId: 'international-student-4a94a',
    storageBucket: 'international-student-4a94a.appspot.com',
    iosClientId: '624595173117-nlpmsslurjvq7qjjvbtmpbdqqn4miec6.apps.googleusercontent.com',
    iosBundleId: 'com.akmilabs.internationalStudentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtH1JX6aBVbfLa3Cru5h09A3a7PQGTO9U',
    appId: '1:624595173117:ios:7b26dc14708f9d83484894',
    messagingSenderId: '624595173117',
    projectId: 'international-student-4a94a',
    storageBucket: 'international-student-4a94a.appspot.com',
    iosClientId: '624595173117-au9q8e4hd9a7rllu57u16hsv9v7jo02f.apps.googleusercontent.com',
    iosBundleId: 'com.akmilabs.internationalStudentApp.RunnerTests',
  );
}
